# Generated by Django 6.0.5 on 2026-06-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_owner_lesson_owner'),
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_status',
            field=models.CharField(
                choices=[
                    ('pending',
                     'Ожидает оплаты'),
                    ('paid',
                     'Оплачено'),
                    ('failed',
                     'Ошибка')],
                default='pending',
                max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cash',
                     'Наличные'),
                    ('transfer',
                     'Перевод на счёт'),
                    ('card',
                     'Банковская карта')],
                default='card',
                max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'paid_course', 'stripe_session_id')},
        ),
    ]
